export { Page as Login } from './login/Page'
export { Page as Layout } from './layout/Page'
export { Page as Oops } from './oops/Page'
export { Page as WishList } from './wishes/list/Page'
export { Page as NewWish } from './wishes/new/Page'
export { Page as EditWish } from './wishes/edit/Page'
export { Page as NewFamily } from './families/new/Page'
export { Page as EditFamily } from './families/edit/Page'
